# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1397727874);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1397727994);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1397727754);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"ru@dictionaries.addons.mozilla.org\":{\"version\":\"0.4.5\",\"type\":\"dictionary\",\"descriptor\":\"/home/administrator/.thunderbird/y9azsex0.default/extensions/ru@dictionaries.addons.mozilla.org\"},\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"24.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\"},\"langpack-ru@thunderbird.mozilla.org\":{\"version\":\"24.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-ru@thunderbird.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "edsintegration%40mozilla.com:0.6,messagingmenu%40mozilla.com:1.3.1,mintrayr%40tn123.ath.cx:1.1.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.4.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1397631898000,\"rdfTime\":1395105789000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"mtime\":1395106479000},\"edsintegration@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/edsintegration@mozilla.com.xpi\",\"mtime\":1395106051000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1395106050000},\"langpack-ru@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-ru@thunderbird.mozilla.org.xpi\",\"mtime\":1395106538000}}},{\"name\":\"app-profile\",\"addons\":{\"ru@dictionaries.addons.mozilla.org\":{\"descriptor\":\"/home/administrator/.thunderbird/y9azsex0.default/extensions/ru@dictionaries.addons.mozilla.org\",\"mtime\":1397642241000,\"rdfTime\":1372535443000},\"mintrayr@tn123.ath.cx\":{\"descriptor\":\"/home/administrator/.thunderbird/y9azsex0.default/extensions/mintrayr@tn123.ath.cx\",\"mtime\":1397642430000,\"rdfTime\":1353464794000}}}]");
user_pref("extensions.lastAppVersion", "24.4.0");
user_pref("extensions.lastPlatformVersion", "24.4.0");
user_pref("extensions.mintrayr.dblclickrestore", false);
user_pref("extensions.mintrayr.minimizeon", 2);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("font.name.monospace.x-cyrillic", "Liberation Mono");
user_pref("font.name.sans-serif.x-cyrillic", "Liberation Sans");
user_pref("font.name.serif.x-cyrillic", "Liberation Serif");
user_pref("font.size.fixed.x-cyrillic", 10);
user_pref("idle.lastDailyNotification", 1397729513);
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.SpellCheckBeforeSend", true);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.inline_attachments", false);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.compose.selectedTabIndex", 0);
user_pref("mail.preferences.display.selectedTabIndex", 0);
user_pref("mail.preferences.security.selectedTabIndex", 4);
user_pref("mail.spam.manualMark", true);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "2b473711-13d3-4657-88ae-79463868c4d");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "24.4.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("plugin.importedState", true);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("security.disable_button.openCertManager", false);
user_pref("spellchecker.dictionary", "ru");
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.telemetry.enabled", true);
user_pref("toolkit.telemetry.previousBuildID", "20140318005459");
user_pref("toolkit.telemetry.prompted", 2);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
